#ifndef LOW_LEVEL_PROGRAMMING3_COMPARE_H
#define LOW_LEVEL_PROGRAMMING3_COMPARE_H
enum compare {
    COMPARE_EQUAL = '=',
    COMPARE_LESS = '<',
    COMPARE_GREATER = '>',
    COMPARE_SUBSTR = ':'
};
#endif //LOW_LEVEL_PROGRAMMING3_COMPARE_H
