#ifndef LOW_LEVEL_PROGRAMMING3_FIELD_TYPES_H
#define LOW_LEVEL_PROGRAMMING3_FIELD_TYPES_H

enum field_types {
    STRING_TYPE = 0,
    INTEGER_TYPE,
    FLOAT_TYPE,
    BOOLEAN_TYPE
};

#endif //LOW_LEVEL_PROGRAMMING3_FIELD_TYPES_H
