// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "request.hxx"

// header_t
// 

const header_t::col_amount_type& header_t::
col_amount () const
{
  return this->col_amount_.get ();
}

header_t::col_amount_type& header_t::
col_amount ()
{
  return this->col_amount_.get ();
}

void header_t::
col_amount (const col_amount_type& x)
{
  this->col_amount_.set (x);
}

const header_t::column_sequence& header_t::
column () const
{
  return this->column_;
}

header_t::column_sequence& header_t::
column ()
{
  return this->column_;
}

void header_t::
column (const column_sequence& s)
{
  this->column_ = s;
}


// body_t
// 

const body_t::nodes_sequence& body_t::
nodes () const
{
  return this->nodes_;
}

body_t::nodes_sequence& body_t::
nodes ()
{
  return this->nodes_;
}

void body_t::
nodes (const nodes_sequence& s)
{
  this->nodes_ = s;
}


// node_t
// 

const node_t::name_type& node_t::
name () const
{
  return this->name_.get ();
}

node_t::name_type& node_t::
name ()
{
  return this->name_.get ();
}

void node_t::
name (const name_type& x)
{
  this->name_.set (x);
}

void node_t::
name (::std::auto_ptr< name_type > x)
{
  this->name_.set (x);
}

const node_t::attr_name_sequence& node_t::
attr_name () const
{
  return this->attr_name_;
}

node_t::attr_name_sequence& node_t::
attr_name ()
{
  return this->attr_name_;
}

void node_t::
attr_name (const attr_name_sequence& s)
{
  this->attr_name_ = s;
}

const node_t::attr_value_sequence& node_t::
attr_value () const
{
  return this->attr_value_;
}

node_t::attr_value_sequence& node_t::
attr_value ()
{
  return this->attr_value_;
}

void node_t::
attr_value (const attr_value_sequence& s)
{
  this->attr_value_ = s;
}


// response_t
// 

const response_t::status_type& response_t::
status () const
{
  return this->status_.get ();
}

response_t::status_type& response_t::
status ()
{
  return this->status_.get ();
}

void response_t::
status (const status_type& x)
{
  this->status_.set (x);
}

const response_t::message_type& response_t::
message () const
{
  return this->message_.get ();
}

response_t::message_type& response_t::
message ()
{
  return this->message_.get ();
}

void response_t::
message (const message_type& x)
{
  this->message_.set (x);
}

void response_t::
message (::std::auto_ptr< message_type > x)
{
  this->message_.set (x);
}

const response_t::finished_type& response_t::
finished () const
{
  return this->finished_.get ();
}

response_t::finished_type& response_t::
finished ()
{
  return this->finished_.get ();
}

void response_t::
finished (const finished_type& x)
{
  this->finished_.set (x);
}

const response_t::header_optional& response_t::
header () const
{
  return this->header_;
}

response_t::header_optional& response_t::
header ()
{
  return this->header_;
}

void response_t::
header (const header_type& x)
{
  this->header_.set (x);
}

void response_t::
header (const header_optional& x)
{
  this->header_ = x;
}

void response_t::
header (::std::auto_ptr< header_type > x)
{
  this->header_.set (x);
}

const response_t::body_optional& response_t::
body () const
{
  return this->body_;
}

response_t::body_optional& response_t::
body ()
{
  return this->body_;
}

void response_t::
body (const body_type& x)
{
  this->body_.set (x);
}

void response_t::
body (const body_optional& x)
{
  this->body_ = x;
}

void response_t::
body (::std::auto_ptr< body_type > x)
{
  this->body_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// header_t
//

header_t::
header_t (const col_amount_type& col_amount)
: ::xml_schema::type (),
  col_amount_ (col_amount, this),
  column_ (this)
{
}

header_t::
header_t (const header_t& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  col_amount_ (x.col_amount_, f, this),
  column_ (x.column_, f, this)
{
}

header_t::
header_t (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  col_amount_ (this),
  column_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void header_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // col_amount
    //
    if (n.name () == "col_amount" && n.namespace_ ().empty ())
    {
      if (!col_amount_.present ())
      {
        this->col_amount_.set (col_amount_traits::create (i, f, this));
        continue;
      }
    }

    // column
    //
    if (n.name () == "column" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< column_type > r (
        column_traits::create (i, f, this));

      this->column_.push_back (r);
      continue;
    }

    break;
  }

  if (!col_amount_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "col_amount",
      "");
  }
}

header_t* header_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class header_t (*this, f, c);
}

header_t& header_t::
operator= (const header_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->col_amount_ = x.col_amount_;
    this->column_ = x.column_;
  }

  return *this;
}

header_t::
~header_t ()
{
}

// body_t
//

body_t::
body_t ()
: ::xml_schema::type (),
  nodes_ (this)
{
}

body_t::
body_t (const body_t& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  nodes_ (x.nodes_, f, this)
{
}

body_t::
body_t (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  nodes_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void body_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // nodes
    //
    if (n.name () == "nodes" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< nodes_type > r (
        nodes_traits::create (i, f, this));

      this->nodes_.push_back (r);
      continue;
    }

    break;
  }
}

body_t* body_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class body_t (*this, f, c);
}

body_t& body_t::
operator= (const body_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->nodes_ = x.nodes_;
  }

  return *this;
}

body_t::
~body_t ()
{
}

// node_t
//

node_t::
node_t (const name_type& name)
: ::xml_schema::type (),
  name_ (name, this),
  attr_name_ (this),
  attr_value_ (this)
{
}

node_t::
node_t (const node_t& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  name_ (x.name_, f, this),
  attr_name_ (x.attr_name_, f, this),
  attr_value_ (x.attr_value_, f, this)
{
}

node_t::
node_t (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  name_ (this),
  attr_name_ (this),
  attr_value_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void node_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // name
    //
    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< name_type > r (
        name_traits::create (i, f, this));

      if (!name_.present ())
      {
        this->name_.set (r);
        continue;
      }
    }

    // attr_name
    //
    if (n.name () == "attr_name" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< attr_name_type > r (
        attr_name_traits::create (i, f, this));

      this->attr_name_.push_back (r);
      continue;
    }

    // attr_value
    //
    if (n.name () == "attr_value" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< attr_value_type > r (
        attr_value_traits::create (i, f, this));

      this->attr_value_.push_back (r);
      continue;
    }

    break;
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "name",
      "");
  }
}

node_t* node_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class node_t (*this, f, c);
}

node_t& node_t::
operator= (const node_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->name_ = x.name_;
    this->attr_name_ = x.attr_name_;
    this->attr_value_ = x.attr_value_;
  }

  return *this;
}

node_t::
~node_t ()
{
}

// response_t
//

response_t::
response_t (const status_type& status,
            const message_type& message,
            const finished_type& finished)
: ::xml_schema::type (),
  status_ (status, this),
  message_ (message, this),
  finished_ (finished, this),
  header_ (this),
  body_ (this)
{
}

response_t::
response_t (const response_t& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  status_ (x.status_, f, this),
  message_ (x.message_, f, this),
  finished_ (x.finished_, f, this),
  header_ (x.header_, f, this),
  body_ (x.body_, f, this)
{
}

response_t::
response_t (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  status_ (this),
  message_ (this),
  finished_ (this),
  header_ (this),
  body_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void response_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // status
    //
    if (n.name () == "status" && n.namespace_ ().empty ())
    {
      if (!status_.present ())
      {
        this->status_.set (status_traits::create (i, f, this));
        continue;
      }
    }

    // message
    //
    if (n.name () == "message" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< message_type > r (
        message_traits::create (i, f, this));

      if (!message_.present ())
      {
        this->message_.set (r);
        continue;
      }
    }

    // finished
    //
    if (n.name () == "finished" && n.namespace_ ().empty ())
    {
      if (!finished_.present ())
      {
        this->finished_.set (finished_traits::create (i, f, this));
        continue;
      }
    }

    // header
    //
    if (n.name () == "header" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< header_type > r (
        header_traits::create (i, f, this));

      if (!this->header_)
      {
        this->header_.set (r);
        continue;
      }
    }

    // body
    //
    if (n.name () == "body" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< body_type > r (
        body_traits::create (i, f, this));

      if (!this->body_)
      {
        this->body_.set (r);
        continue;
      }
    }

    break;
  }

  if (!status_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "status",
      "");
  }

  if (!message_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "message",
      "");
  }

  if (!finished_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "finished",
      "");
  }
}

response_t* response_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class response_t (*this, f, c);
}

response_t& response_t::
operator= (const response_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->status_ = x.status_;
    this->message_ = x.message_;
    this->finished_ = x.finished_;
    this->header_ = x.header_;
    this->body_ = x.body_;
  }

  return *this;
}

response_t::
~response_t ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::auto_ptr< ::response_t >
resp (const ::std::string& u,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::auto_ptr< ::response_t > (
    ::resp (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::response_t >
resp (const ::std::string& u,
      ::xml_schema::error_handler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::response_t > (
    ::resp (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::response_t >
resp (const ::std::string& u,
      ::xercesc::DOMErrorHandler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::response_t > (
    ::resp (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::response_t >
resp (::std::istream& is,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::resp (isrc, f, p);
}

::std::auto_ptr< ::response_t >
resp (::std::istream& is,
      ::xml_schema::error_handler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::resp (isrc, h, f, p);
}

::std::auto_ptr< ::response_t >
resp (::std::istream& is,
      ::xercesc::DOMErrorHandler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::resp (isrc, h, f, p);
}

::std::auto_ptr< ::response_t >
resp (::std::istream& is,
      const ::std::string& sid,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::resp (isrc, f, p);
}

::std::auto_ptr< ::response_t >
resp (::std::istream& is,
      const ::std::string& sid,
      ::xml_schema::error_handler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::resp (isrc, h, f, p);
}

::std::auto_ptr< ::response_t >
resp (::std::istream& is,
      const ::std::string& sid,
      ::xercesc::DOMErrorHandler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::resp (isrc, h, f, p);
}

::std::auto_ptr< ::response_t >
resp (::xercesc::InputSource& i,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::auto_ptr< ::response_t > (
    ::resp (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::response_t >
resp (::xercesc::InputSource& i,
      ::xml_schema::error_handler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::response_t > (
    ::resp (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::response_t >
resp (::xercesc::InputSource& i,
      ::xercesc::DOMErrorHandler& h,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::response_t > (
    ::resp (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::response_t >
resp (const ::xercesc::DOMDocument& doc,
      ::xml_schema::flags f,
      const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::auto_ptr< ::response_t > (
      ::resp (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "resp" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::response_t > r (
      ::xsd::cxx::tree::traits< ::response_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "resp",
    "");
}

::std::auto_ptr< ::response_t >
resp (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
      ::xml_schema::flags f,
      const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "resp" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::response_t > r (
      ::xsd::cxx::tree::traits< ::response_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "resp",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

void
operator<< (::xercesc::DOMElement& e, const header_t& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // col_amount
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "col_amount",
        e));

    s << i.col_amount ();
  }

  // column
  //
  for (header_t::column_const_iterator
       b (i.column ().begin ()), n (i.column ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "column",
        e));

    s << *b;
  }
}

void
operator<< (::xercesc::DOMElement& e, const body_t& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // nodes
  //
  for (body_t::nodes_const_iterator
       b (i.nodes ().begin ()), n (i.nodes ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "nodes",
        e));

    s << *b;
  }
}

void
operator<< (::xercesc::DOMElement& e, const node_t& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // name
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "name",
        e));

    s << i.name ();
  }

  // attr_name
  //
  for (node_t::attr_name_const_iterator
       b (i.attr_name ().begin ()), n (i.attr_name ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "attr_name",
        e));

    s << *b;
  }

  // attr_value
  //
  for (node_t::attr_value_const_iterator
       b (i.attr_value ().begin ()), n (i.attr_value ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "attr_value",
        e));

    s << *b;
  }
}

void
operator<< (::xercesc::DOMElement& e, const response_t& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // status
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "status",
        e));

    s << i.status ();
  }

  // message
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "message",
        e));

    s << i.message ();
  }

  // finished
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "finished",
        e));

    s << i.finished ();
  }

  // header
  //
  if (i.header ())
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "header",
        e));

    s << *i.header ();
  }

  // body
  //
  if (i.body ())
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "body",
        e));

    s << *i.body ();
  }
}

void
resp (::std::ostream& o,
      const ::response_t& s,
      const ::xml_schema::namespace_infomap& m,
      const ::std::string& e,
      ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::resp (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
resp (::std::ostream& o,
      const ::response_t& s,
      ::xml_schema::error_handler& h,
      const ::xml_schema::namespace_infomap& m,
      const ::std::string& e,
      ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::resp (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
resp (::std::ostream& o,
      const ::response_t& s,
      ::xercesc::DOMErrorHandler& h,
      const ::xml_schema::namespace_infomap& m,
      const ::std::string& e,
      ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::resp (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
resp (::xercesc::XMLFormatTarget& t,
      const ::response_t& s,
      const ::xml_schema::namespace_infomap& m,
      const ::std::string& e,
      ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::resp (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
resp (::xercesc::XMLFormatTarget& t,
      const ::response_t& s,
      ::xml_schema::error_handler& h,
      const ::xml_schema::namespace_infomap& m,
      const ::std::string& e,
      ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::resp (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
resp (::xercesc::XMLFormatTarget& t,
      const ::response_t& s,
      ::xercesc::DOMErrorHandler& h,
      const ::xml_schema::namespace_infomap& m,
      const ::std::string& e,
      ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::resp (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
resp (::xercesc::DOMDocument& d,
      const ::response_t& s,
      ::xml_schema::flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "resp" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "resp",
      "");
  }
}

::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
resp (const ::response_t& s,
      const ::xml_schema::namespace_infomap& m,
      ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "resp",
      "",
      m, f));

  ::resp (*d, s, f);
  return d;
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

